# Generated by Django 4.0.5 on 2022-06-28 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_product_is_active"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="user",
            new_name="seller",
        ),
    ]
